apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagdusheth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagdusheth-app
  template:
    metadata:
      labels:
        app: dagdusheth-app
    spec:
      containers:
      - name: dagdusheth-app
        image: 984124409676.dkr.ecr.ap-south-1.amazonaws.com/dagdusheth-app:latest
        ports:
        - containerPort: 80
